### ISSUE TITLE
Antimeridian issues in version 0-4-11

### ISSUE THREAD

**Issue by alexgleith** [digitalearthpacific/dep-coastlines#28]
We have antimeridian geometry issues in version `0.4.1` for example, in tile `73/71`, image below.

<img width="550" alt="image" src="https://github.com/digitalearthpacific/dep-coastlines/assets/3445853/932d4f42-c54d-4b89-b31e-858e254bc55e">

Here's a link to the file: https://deppcpublicstorage.blob.core.windows.net/output/coastlines/0-4-11/mndwi-clean-lines/mndwi-clean-lines_73_71.gpkg

We should make sure we're writing data without issues, so that we can be careful when reading it and also not introduce issues, I think.

**Comment by jessjaco** [comment]
Data are in UTM, how can they have antimeridian issues

**Comment by alexgleith** [comment]
True, it was caused by me using QGIS in a non-native projection. Sorry!
